import { 
  renderInputPanel,
  renderResultSummary, 
  renderAssumptions,
  setInputValues,
  getInputValues,
  updateStickyBar,
  ICONS
} from '../utils/ui.js';
import { saveInputs, loadInputs } from '../utils/storage.js';
import { LIVE_LOADS } from '../data/loads.js';

const MODULE_ID = 'live-load';

// Get unique groups
const groups = [...new Set(LIVE_LOADS.map(l => l.group))];

const INPUT_FIELDS_LOOKUP = [
  { id: 'group', label: 'Building Occupancy Type', type: 'select', 
    options: [{value: '', label: '-- Select Occupancy --'}, ...groups.map(g => ({value: g, label: g}))] },
  { id: 'usage', label: 'Specific Room / Area Usage', type: 'select', 
    options: [{value: '', label: '-- Select Usage --'}] }
];

function renderLiveLoadResult(loadData) {
  const container = document.getElementById('live-load-result-box');
  
  if (!loadData) {
    container.innerHTML = '';
    updateStickyBar([]);
    return;
  }
  
  const factoredUDL = loadData.udl * 1.5;
  
  const summaryCards = [
    {
      label: 'UDL (Uniformly Distributed)',
      value: loadData.udl.toFixed(2) + ' kN/m²',
      sub: 'Factored: ' + factoredUDL.toFixed(2),
      status: 'pass'
    },
    {
      label: 'Concentrated Point Load',
      value: loadData.point.toFixed(2) + ' kN',
      status: 'info'
    }
  ];
  
  container.innerHTML = `
    <div class="calculator-layout" style="margin-top: 2rem;">
      <div class="results-main">
        <div class="results-panel" style="margin-top: 0;">
          <div class="results-panel__header">
            <h3>Live Load Limits (IS 875 Part 2)</h3>
          </div>
          ${renderResultSummary(summaryCards)}
        </div>
      </div>
    </div>
  `;
  
  updateStickyBar([
    { label: 'Occupancy', value: loadData.group },
    { label: 'Usage', value: loadData.usage.split(',')[0] },
    { label: 'UDL', value: loadData.udl.toFixed(2) + ' kN/m²' }
  ]);
}

export function initLiveLoad(container) {
  container.innerHTML = `
    <div class="calculator-page" id="live-load-calc">
      <div class="print-header">
        <div class="print-header__brand">Stellar Civil — Live Load Reference</div>
        <div class="print-header__info"></div>
      </div>

      <div class="calculator-page__header">
        <h2>Live Load Reference</h2>
        <p>Quickly lookup imposed loads for various building occupancies.</p>
        <span class="calculator-page__code-ref">
          ${ICONS.info} IS 875 (Part 2): 1987
        </span>
      </div>

      ${renderAssumptions([
        'Values represent basic characteristic imposed loads without area reductions',
        'For design, these characteristic loads should be multiplied by appropriate partial safety factors (γf)'
      ])}

      ${renderInputPanel('Occupancy Category', INPUT_FIELDS_LOOKUP, ICONS.building)}

      <div id="live-load-result-box"></div>

      <div class="print-footer">
        Generated by Stellar Civil | For reference only. Verify with qualified engineer.
      </div>
    </div>
  `;
  
  const groupSelect = container.querySelector('#group');
  const usageSelect = container.querySelector('#usage');
  
  if (usageSelect && !usageSelect.options.length > 1) {
    usageSelect.disabled = true;
  }
  
  function populateUsages(selectedGroup, defaultUsage = '') {
    const usages = LIVE_LOADS.filter(l => l.group === selectedGroup);
    usageSelect.innerHTML = '<option value="">-- Select Usage --</option>' + 
      usages.map(u => `<option value="${u.usage}">${u.usage}</option>`).join('');
    
    usageSelect.disabled = usages.length === 0;
    if (defaultUsage) usageSelect.value = defaultUsage;
  }
  
  groupSelect.addEventListener('change', (e) => {
    populateUsages(e.target.value);
    renderLiveLoadResult(null);
    saveInputs(MODULE_ID, { group: e.target.value, usage: '' });
  });
  
  usageSelect.addEventListener('change', (e) => {
    const group = groupSelect.value;
    const usage = e.target.value;
    saveInputs(MODULE_ID, { group, usage });
    
    if (group && usage) {
      const load = LIVE_LOADS.find(l => l.group === group && l.usage === usage);
      renderLiveLoadResult(load);
    } else {
      renderLiveLoadResult(null);
    }
  });
  
  const saved = loadInputs(MODULE_ID);
  if (saved && saved.group) {
    groupSelect.value = saved.group;
    populateUsages(saved.group, saved.usage);
    if (saved.usage) {
      const load = LIVE_LOADS.find(l => l.group === saved.group && l.usage === saved.usage);
      if (load) renderLiveLoadResult(load);
    }
  }
}
